---
version: '2.0'
services:
  gql-db:
    image: postgres:11.5
    restart: always
    # opening port for development use
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      # - './scripts/seed-todos.sql:/docker-entrypoint-initdb.d/seed-todos.sql'
    environment:
      POSTGRES_USER: cathy
      POSTGRES_PASSWORD: password

  gql-service:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: 'yarn start:dev'
    environment:
      POSTGRES_HOST: gql-db
      POSTGRES_USER: cathy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cathy
    depends_on:
      - gql-db

volumes:
  postgres:
    